### ISSUE TITLE
USE_TRAINER_PROB is not in the python parameters.

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#20]
https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/table/wikisql/run.sh

USE_TRAINER_PROB is defined above, but is not used in the python related command below.

**Comment by crazydonkey200** [comment]
Thanks for pointing this out. It might be left out when cleaning up the commandlines. I have just added it back.
