### ISSUE TITLE
use more than 1 gpu

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#22]
![image](https://user-images.githubusercontent.com/4702353/58773880-6cc56880-85f1-11e9-98e9-03d61643ede6.png)

with `export CUDA_VISIBLE_DEVICES=0`

and

![image](https://user-images.githubusercontent.com/4702353/58773942-bd3cc600-85f1-11e9-866b-ef4b9e5405c2.png)

**Comment by crazydonkey200** [comment]
I think `export CUDA_VISIBLE_DEVICES=0` only exposes 1 GPU, so you shouldn't have it here. See [this stackoverflow thread](https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on/39661999).

**Comment by guotong1988** [comment]
Thank you! I mean, what is the best usage for this code, 1 gpu or multi-gpu?

**Comment by guotong1988** [comment]
I intent to use 1 gpu, not multi gpu.

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/59177316-3f972e00-8b8e-11e9-9d8a-9be80eb49362.png)

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/59177327-4faf0d80-8b8e-11e9-8bca-e5c71d9f22de.png)
