### ISSUE TITLE
The paper says it also need a number of labeled SQL to train?

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#24]
![image](https://user-images.githubusercontent.com/4702353/58774217-e6aa2180-85f2-11e9-81fc-a33ef0dae73a.png)

Thank you very much.

**Comment by guotong1988** [comment]
Am I right?

**Comment by crazydonkey200** [comment]
Hi, the model doesn't need labeled SQL to train. It only uses question and answer pairs as weak supervision. Please see Section 4 for more details.

**Comment by guotong1988** [comment]
Thank you！

**Comment by guotong1988** [comment]
What does `load_programs` in `experiment.py` do?
@crazydonkey200 Thank you!
![image](https://user-images.githubusercontent.com/4702353/59183202-15e60300-8b9e-11e9-80b0-27690a79bca8.png)

**Comment by crazydonkey200** [comment]
It refers to programs found from random search, see section 5.1 training details.
