### ISSUE TITLE
NSM also use database table header to train, am I right?

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#28]
In Wikisql.
Not only question-answer pair.
Thank you!

**Comment by crazydonkey200** [comment]
No, it doesn't use table headers.

**Comment by guotong1988** [comment]
Thank you.
It is amazing. How could NSM generate the SQL without using table headers.
NSM do not know how to interact with the database without the table headers, based on my understanding.

**Comment by guotong1988** [comment]
My understanding: 

NSM use the reward of SQL execution to train and then to find the right SQL with right answer.

The reward come from the execution result of SQL and the labeled answer.

**Comment by crazydonkey200** [comment]
NSM uses the column names when generating the programs if that's what you mean by "table header". You can see that from the example programs in Supplementary B of the paper.

**Comment by guotong1988** [comment]
thank you very much
