### ISSUE TITLE
Hard to find the code where the reward guide the training.

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#29]
Sorry to trouble you, but there are too much code.
Would you please point out the code place about the core of REINFORCE algorithm.
Thank you very much.

**Comment by crazydonkey200** [comment]
https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/nsm/agent_factory.py#L137

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/59259471-73488580-8c6c-11e9-9a6a-0e7853d036dd.png)
Thank you very much!
