### ISSUE TITLE
Imported modules not defined

### ISSUE THREAD

**Issue by theSparta** [crazydonkey200/neural-symbolic-machines#3]
```
import wtq_evaluator
import wtq_utils
```
In the file [preprocess.py](../blob/master/table/wtq/preprocess.py), the above modules are imported but not defined. I guess the correct imports should be:
```
import evaluator as wtq_evaluator
import ..utils as wtq_utils
```

**Comment by crazydonkey200** [comment]
Thanks for reporting the problem! Just fixed here [https://github.com/crazydonkey200/neural-symbolic-machines/commit/7e335162ba937acb17fa55c216a5fcda4252f82c](url).

**Comment by crazydonkey200** [comment]
Closing for now. Feel free to reopen if there are more questions :)
