### ISSUE TITLE
What is the ValueEstimator of NSM?

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#30]
I read that REINFORCE algorithm have a ValueApproximator and a PolicyEstimator.
Thank you!

**Comment by crazydonkey200** [comment]
Actor-Critic has value estimator, REINFORCE doesn't.

**Comment by guotong1988** [comment]
Thank you, very very much.

**Comment by guotong1988** [comment]
Thank you, I read from here:
https://github.com/dennybritz/reinforcement-learning/blob/master/PolicyGradient/CliffWalk%20REINFORCE%20with%20Baseline%20Solution.ipynb
