### ISSUE TITLE
Why targets=actions?

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#31]
![image](https://user-images.githubusercontent.com/4702353/59320814-447cee80-8d02-11e9-9388-97696e48ada4.png)
In https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/nsm/agent_factory.py

![image](https://user-images.githubusercontent.com/4702353/59665118-dd20dc00-91e4-11e9-87eb-f47b7ec558bf.png)
In https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/nsm/model_factory.py

I guess `targets` should at least be related to rewards.
Thank you!!

**Comment by crazydonkey200** [comment]
The reward is provided through the `weights`. The `targets` are the actions. You can think of REINFORCE as a weighted log-likelihood training where the reward or advantage times probability is used as the weight and the action is used as the target.

**Comment by guotong1988** [comment]
thank you very much
