### ISSUE TITLE
For Wikisql, different agg may lead to same result. How do you deal with this problem?

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#34]
Thank you!

**Comment by crazydonkey200** [comment]
I didn't do anything special for this. A program that gets the right answer, no matter which agg it uses, will receive a good reward. It is related to the spurious program problem discussed in the [MAPO](http://papers.nips.cc/paper/8204-memory-augmented-policy-optimization-for-program-synthesis-and-semantic-parsing) paper and [this paper](https://arxiv.org/abs/1606.06900).
