### ISSUE TITLE
The experiment on WebquestionSP

### ISSUE THREAD

**Issue by Snnzhao** [crazydonkey200/neural-symbolic-machines#42]
Could you please also publish the experiment on WebquestionSP?

**Comment by crazydonkey200** [comment]
For WebQuestionSP experiments, we used Google's internal infra to serve the Freebase (pruned by removing some irrelevant parts to reduce the size, more details in the paper) for fast querying, which unfortunately could not be open sourced (and also would not run without the Google infra). 

For open source solutions, an in-memory key-value DB might be a good alternative if you have enough memory. If you don't have enough memory to hold the whole Freebase, one solution you could consider is to use virtuoso to query over all the relevant intermediate entities in the dataset once, save the results, and then hold them in memory as key-value pairs for faster querying. 

Hope this helps!

**Comment by Snnzhao** [comment]
Thanks for your reply.
