### ISSUE TITLE
Different vocab for different en_vocab files.

### ISSUE THREAD

**Issue by theSparta** [crazydonkey200/neural-symbolic-machines#7]
https://github.com/crazydonkey200/neural-symbolic-machines/blob/231bdc38ea2d84c3dcc883c3fd5cd2107f3d53b4/nsm/word_embeddings.py#L14-L16

Due to the above line, the vocab in embedding model i.e. `embedding_model.vocab` is different (i.e mapping from token to index would be different) depending on the `en_vocab_count_i.json` file you use (I tried it for `i = 1, 5`). 

This doesn't seem right because the embeddings loaded for a given token would be dependent on the vocabulary you used.
https://github.com/crazydonkey200/neural-symbolic-machines/blob/231bdc38ea2d84c3dcc883c3fd5cd2107f3d53b4/nsm/word_embeddings.py#L21-L24

**Comment by crazydonkey200** [comment]
There are two vocab files used as input to `experiment.py`, and they served two different purposes. 

(1) `vocab_file`: From all the words in the GloVe vocabulary, we just need those that appear in our dataset (WikiSQL or WikiTable). So `vocab_file` (for example, `raw_input/wikisql_glove_vocab.json`) contains a list of words that appear in the dataset and `embedding_file` (for example, `raw_input/wikisql_glove_embedding_mat.npy`) contains a matrix of the corresponding GloVe embeddings for the words. This way the users don't need to download and load the original GloVe embeddings file, which is usually quite large.  

(2) `en_vocab_file`: a vocabulary of the most frequent words to turn questions into ids. This is specified by `en_vocab_file`, and is using the `en_vocab_count_i.json` files. 

To answer your question, `en_vocab_count_i.json` are not used as the `vocab_file` but as the `en_vocab_file`. You can verify this by looking at how the EmbeddingModel is initialized and what is passed as argument for `vocab_file` and `en_vocab_file` (check out the links below). 

https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/table/experiment.py#L522

https://github.com/crazydonkey200/neural-symbolic-machines/blob/master/table/wikisql/run.sh#L61
